# -*- coding: utf-8 -*-
"""Financial_Statement_Automator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z7bnBdSdqsaiT95eQkTw2suC_d6t6B9U
"""

import customtkinter as ctk
import tkinter as tk
from tkinter import filedialog, messagebox
import os
import pandas as pd # Assuming pandas will be used for data handling

class FinancialStatementGeneratorApp(ctk.CTk):
    def __init__(self):
        super().__init__()

        # Configure window
        self.title("Audited Financial Statement Generator (ICAI & Schedule III)")
        self.geometry("1200x800")

        # Set grid layout for main window
        self.grid_rowconfigure(0, weight=1)
        self.grid_columnconfigure(0, weight=1)

        # Create tabview for steps
        self.tabview = ctk.CTkTabview(self, width=250)
        self.tabview.grid(row=0, column=0, padx=20, pady=20, sticky="nsew")

        # Step 1: Entity Profile
        self.tabview.add("1. Entity Profile")
        self.tabview.tab("1. Entity Profile").grid_columnconfigure(0, weight=1)
        self.create_entity_profile_tab()

        # Step 2: Formatting Master
        self.tabview.add("2. Formatting Master")
        self.tabview.tab("2. Formatting Master").grid_columnconfigure(0, weight=1)
        self.create_formatting_master_tab()

        # Step 3: Prior Year Figures (Optional)
        self.tabview.add("3. Prior Year Figures")
        self.tabview.tab("3. Prior Year Figures").grid_columnconfigure(0, weight=1)
        self.create_prior_year_figures_tab()

        # Step 4: Current Year Data Ingestion
        self.tabview.add("4. Current Year Data")
        self.tabview.tab("4. Current Year Data").grid_columnconfigure(0, weight=1)
        self.create_current_year_data_tab()

        # Step 5: Depreciation Engine Options
        self.tabview.add("5. Depreciation")
        self.tabview.tab("5. Depreciation").grid_columnconfigure(0, weight=1)
        self.create_depreciation_options_tab()

        # Action Area (outside tabview, or as a final tab)
        self.tabview.add("6. Generate")
        self.tabview.tab("6. Generate").grid_columnconfigure(0, weight=1)
        self.create_action_area_tab()

        # Store file paths (full paths, not just basenames)
        self.file_paths = {
            "custom_formatting_file": None,
            "prior_year_financials_file": None,
            "current_year_trial_balance_file": None,
            "current_year_draft_bs_pl_file": None,
            "income_tax_block_register_file": None,
            "schedule_ii_asset_register_file": None,
            "income_tax_wdv_schedule_file": None,
        }

    def create_entity_profile_tab(self):
        tab = self.tabview.tab("1. Entity Profile")

        # Inputs: Entity Name, Assessment Year, Financial Year
        ctk.CTkLabel(tab, text="Entity Name:").grid(row=0, column=0, padx=10, pady=5, sticky="w")
        self.entity_name_entry = ctk.CTkEntry(tab, width=300)
        self.entity_name_entry.grid(row=0, column=1, padx=10, pady=5, sticky="ew")

        ctk.CTkLabel(tab, text="Assessment Year:").grid(row=1, column=0, padx=10, pady=5, sticky="w")
        self.assessment_year_entry = ctk.CTkEntry(tab, width=300)
        self.assessment_year_entry.grid(row=1, column=1, padx=10, pady=5, sticky="ew")

        ctk.CTkLabel(tab, text="Financial Year:").grid(row=2, column=0, padx=10, pady=5, sticky="w")
        self.financial_year_entry = ctk.CTkEntry(tab, width=300)
        self.financial_year_entry.grid(row=2, column=1, padx=10, pady=5, sticky="ew")

        # Entity Type (Dropdown)
        ctk.CTkLabel(tab, text="Entity Type:").grid(row=3, column=0, padx=10, pady=5, sticky="w")
        self.entity_type_options = [
            "Proprietorship",
            "Partnership Firm",
            "Trust",
            "Private Limited / Limited Company"
        ]
        self.entity_type_var = ctk.StringVar(value=self.entity_type_options[0])
        self.entity_type_dropdown = ctk.CTkOptionMenu(tab, values=self.entity_type_options, variable=self.entity_type_var, command=self.update_entity_badge)
        self.entity_type_dropdown.grid(row=3, column=1, padx=10, pady=5, sticky="ew")

        # Dynamic Badge
        self.badge_label = ctk.CTkLabel(tab, text="", wraplength=400, justify="left", fg_color="#336699", text_color="white", corner_radius=5)
        self.badge_label.grid(row=4, column=0, columnspan=2, padx=10, pady=10, sticky="ew")
        self.update_entity_badge(self.entity_type_var.get()) # Initialize badge

    def update_entity_badge(self, selected_type):
        if selected_type in ["Proprietorship", "Partnership Firm", "Trust"]:
            self.badge_label.configure(text="Governed by ICAI AS & Income Tax Act 1961")
        else:
            self.badge_label.configure(text="Governed by Companies Act 2013 (Schedule III Division I) & Dual Depreciation")

    def create_formatting_master_tab(self):
        tab = self.tabview.tab("2. Formatting Master")

        self.formatting_option_var = ctk.StringVar(value="standard")

        # Option A: Radio selection for "Use Standard ICAI / Schedule III Template"
        ctk.CTkRadioButton(tab, text="Use Standard ICAI / Schedule III Template",
                           variable=self.formatting_option_var, value="standard").grid(row=0, column=0, padx=10, pady=10, sticky="w")

        # Option B: File uploader for "Upload Custom Prior Year Client File for Layout & Style Cloning"
        ctk.CTkRadioButton(tab, text="Upload Custom Prior Year Client File for Layout & Style Cloning",
                           variable=self.formatting_option_var, value="custom").grid(row=1, column=0, padx=10, pady=10, sticky="w")
        self.custom_file_path_label = ctk.CTkLabel(tab, text="No file selected")
        self.custom_file_path_label.grid(row=2, column=0, padx=20, pady=5, sticky="w")
        ctk.CTkButton(tab, text="Browse .xlsx", command=lambda: self.select_file(self.custom_file_path_label, ".xlsx", "custom_formatting_file")).grid(row=2, column=1, padx=10, pady=5, sticky="w")

    def create_prior_year_figures_tab(self):
        tab = self.tabview.tab("3. Prior Year Figures")

        self.prior_year_data_available_var = ctk.BooleanVar(value=False)
        self.prior_year_toggle = ctk.CTkSwitch(tab, text="Prior Year Data Available",
                                                 variable=self.prior_year_data_available_var,
                                                 command=self.toggle_prior_year_file_picker)
        self.prior_year_toggle.grid(row=0, column=0, padx=10, pady=10, sticky="w")

        self.prior_year_file_frame = ctk.CTkFrame(tab)
        self.prior_year_file_frame.grid(row=1, column=0, columnspan=2, padx=10, pady=5, sticky="ew")
        self.prior_year_file_frame.grid_columnconfigure(0, weight=1)

        ctk.CTkLabel(self.prior_year_file_frame, text="Audited Financials File:").grid(row=0, column=0, padx=10, pady=5, sticky="w")
        self.prior_year_file_path_label = ctk.CTkLabel(self.prior_year_file_frame, text="No file selected")
        self.prior_year_file_path_label.grid(row=0, column=1, padx=10, pady=5, sticky="ew")
        ctk.CTkButton(self.prior_year_file_frame, text="Browse .xlsx/.pdf",
                      command=lambda: self.select_file(self.prior_year_file_path_label, ".xlsx .pdf", "prior_year_financials_file")).grid(row=0, column=2, padx=10, pady=5, sticky="w")

        # Initially hide the file picker
        self.toggle_prior_year_file_picker()

    def toggle_prior_year_file_picker(self):
        if self.prior_year_data_available_var.get():
            self.prior_year_file_frame.grid()
        else:
            self.prior_year_file_frame.grid_remove()

    def create_current_year_data_tab(self):
        tab = self.tabview.tab("4. Current Year Data")

        self.current_year_source_var = ctk.StringVar(value="trial_balance")

        # Radio selector with 3 sources
        ctk.CTkRadioButton(tab, text="Upload Trial Balance (Excel/CSV)",
                           variable=self.current_year_source_var, value="trial_balance").grid(row=0, column=0, padx=10, pady=5, sticky="w")
        self.trial_balance_path_label = ctk.CTkLabel(tab, text="No file selected")
        self.trial_balance_path_label.grid(row=1, column=0, padx=20, pady=2, sticky="w")
        ctk.CTkButton(tab, text="Browse .xlsx/.csv", command=lambda: self.select_file(self.trial_balance_path_label, ".xlsx .csv", "current_year_trial_balance_file")).grid(row=1, column=1, padx=10, pady=2, sticky="w")

        ctk.CTkRadioButton(tab, text="Upload Draft Balance Sheet & P&L (Excel)",
                           variable=self.current_year_source_var, value="draft_bs_pl").grid(row=2, column=0, padx=10, pady=5, sticky="w")
        self.draft_bs_pl_path_label = ctk.CTkLabel(tab, text="No file selected")
        self.draft_bs_pl_path_label.grid(row=3, column=0, padx=20, pady=2, sticky="w")
        ctk.CTkButton(tab, text="Browse .xlsx", command=lambda: self.select_file(self.draft_bs_pl_path_label, ".xlsx", "current_year_draft_bs_pl_file")).grid(row=3, column=1, padx=10, pady=2, sticky="w")

        ctk.CTkRadioButton(tab, text="Direct Fetch from Tally Prime (Localhost Port 9000)",
                           variable=self.current_year_source_var, value="tally_prime").grid(row=4, column=0, padx=10, pady=5, sticky="w")
        ctk.CTkButton(tab, text="Test Connection", command=self.test_tally_connection).grid(row=5, column=0, padx=20, pady=5, sticky="w")

    def test_tally_connection(self):
        # Placeholder for Tally Prime connection logic
        self.log_message("Attempting to connect to Tally Prime on localhost:9000...")
        # In a real app, this would involve a network request and error handling
        # For now, simulate success or failure
        # import requests
        # try:
        #     response = requests.get('http://localhost:9000/some_tally_api_endpoint', timeout=5)
        #     if response.status_code == 200:
        #         self.log_message("Successfully connected to Tally Prime!")
        #     else:
        #         self.log_message(f"Failed to connect. Status code: {response.status_code}")
        # except requests.exceptions.ConnectionError:
        #     self.log_message("Connection failed. Is Tally Prime running and API enabled?")
        # except requests.exceptions.Timeout:
        #     self.log_message("Connection timed out.")
        self.log_message("Connection test (simulated) complete. Check console for actual results.")
        messagebox.showinfo("Tally Prime", "Connection test (simulated) complete.")

    def create_depreciation_options_tab(self):
        tab = self.tabview.tab("5. Depreciation")

        ctk.CTkLabel(tab, text="Depreciation Engine Options").grid(row=0, column=0, columnspan=2, padx=10, pady=10, sticky="w")

        # For Non-Corporate: Upload Hook for "Income Tax Block Register"
        ctk.CTkLabel(tab, text="Income Tax Block Register (Non-Corporate):").grid(row=1, column=0, padx=10, pady=5, sticky="w")
        self.it_block_register_path_label = ctk.CTkLabel(tab, text="No file selected")
        self.it_block_register_path_label.grid(row=1, column=1, padx=10, pady=5, sticky="ew")
        ctk.CTkButton(tab, text="Browse", command=lambda: self.select_file(self.it_block_register_path_label, ".xlsx", "income_tax_block_register_file")).grid(row=1, column=2, padx=10, pady=5, sticky="w")

        # For Companies: Dual Upload Hooks
        ctk.CTkLabel(tab, text="Schedule II Asset Register (Companies):").grid(row=2, column=0, padx=10, pady=5, sticky="w")
        self.schedule_ii_asset_register_path_label = ctk.CTkLabel(tab, text="No file selected")
        self.schedule_ii_asset_register_path_label.grid(row=2, column=1, padx=10, pady=5, sticky="ew")
        ctk.CTkButton(tab, text="Browse", command=lambda: self.select_file(self.schedule_ii_asset_register_path_label, ".xlsx", "schedule_ii_asset_register_file")).grid(row=2, column=2, padx=10, pady=5, sticky="w")

        ctk.CTkLabel(tab, text="Income Tax WDV Schedule (Companies):").grid(row=3, column=0, padx=10, pady=5, sticky="w")
        self.it_wdv_schedule_path_label = ctk.CTkLabel(tab, text="No file selected")
        self.it_wdv_schedule_path_label.grid(row=3, column=1, padx=10, pady=5, sticky="ew")
        ctk.CTkButton(tab, text="Browse", command=lambda: self.select_file(self.it_wdv_schedule_path_label, ".xlsx", "income_tax_wdv_schedule_file")).grid(row=3, column=2, padx=10, pady=5, sticky="w")

    def create_action_area_tab(self):
        tab = self.tabview.tab("6. Generate")

        # "Generate Financial Statements (.xlsx)" button
        self.generate_button = ctk.CTkButton(tab, text="Generate Financial Statements (.xlsx)", command=self.generate_financial_statements)
        self.generate_button.grid(row=0, column=0, padx=20, pady=20, sticky="ew")

        # Real-time progress bar
        ctk.CTkLabel(tab, text="Progress:").grid(row=1, column=0, padx=10, pady=5, sticky="w")
        self.progress_bar = ctk.CTkProgressBar(tab)
        self.progress_bar.grid(row=2, column=0, padx=20, pady=5, sticky="ew")
        self.progress_bar.set(0)

        # Log window
        ctk.CTkLabel(tab, text="Log:積極的に").grid(row=3, column=0, padx=10, pady=5, sticky="w")
        self.log_textbox = ctk.CTkTextbox(tab, height=200, state="disabled")
        self.log_textbox.grid(row=4, column=0, padx=20, pady=5, sticky="nsew")
        tab.grid_rowconfigure(4, weight=1)

    def log_message(self, message):
        self.log_textbox.configure(state="normal")
        self.log_textbox.insert("end", message + "\n")
        self.log_textbox.see("end") # Auto-scroll to the end
        self.log_textbox.configure(state="disabled")

    def select_file(self, label_widget, file_types, file_key):
        filetypes_list = []
        for ft in file_types.split():
            filetypes_list.append((f"*{ft} files", f"*{ft}"))
        filetypes_list.append(("All files", "*.* "))

        filepath = filedialog.askopenfilename(filetypes=filetypes_list)
        if filepath:
            label_widget.configure(text=os.path.basename(filepath))
            self.file_paths[file_key] = filepath # Store the full path
            self.log_message(f"Selected file for {file_key}: {os.path.basename(filepath)}")
        else:
            label_widget.configure(text="No file selected")
            self.file_paths[file_key] = None # Clear the path if selection is cancelled
            self.log_message(f"File selection cancelled for {file_key}.")

    def _load_standard_template(self, entity_type):
        """
        Loads a standard financial statement template based on entity type.
        This is a placeholder and would load actual Excel templates in a real application.
        """
        self.log_message(f"Loading standard template for {entity_type}...")
        # Define a simplified template structure for demonstration
        template_data = {
            'Category': ['Assets', 'Assets', 'Liabilities', 'Liabilities', 'Income', 'Income', 'Expense', 'Expense'],
            'Sub-Category': ['Fixed Assets', 'Current Assets', 'Share Capital', 'Current Liabilities', 'Revenue', 'Other Income', 'Operating Expenses', 'Other Expenses'],
            'Account Name': ['Plant & Machinery', 'Cash & Bank', 'Equity Shares', 'Creditors', 'Sales', 'Interest Income', 'Salaries', 'Rent'],
            'Mapping Code': ['FA001', 'CA001', 'SC001', 'CL001', 'REV001', 'OI001', 'EXP001', 'EXP002']
        }
        return pd.DataFrame(template_data)

    def _process_prior_year_financials(self, file_path):
        """
        Processes the prior year financial statements from an Excel or PDF file.
        Returns a dictionary or DataFrame containing extracted prior year figures.
        For PDF, this is a simplified simulation.
        """
        prior_year_data = {} # Initialize an empty dictionary for prior year data
        if file_path.lower().endswith('.xlsx'):
            self.log_message(f"Attempting to read prior year Excel file: {os.path.basename(file_path)}")
            try:
                # Assuming the Excel has sheets like 'Balance Sheet', 'P&L', etc.
                # For simplicity, let's just load the first sheet for now.
                prior_year_df = pd.read_excel(file_path)
                prior_year_data['excel_data'] = prior_year_df.to_dict('records') # Store as list of dicts
                self.log_message(f"Successfully loaded prior year data from Excel. Rows: {len(prior_year_df)}")
            except Exception as e:
                self.log_message(f"Error reading prior year Excel file: {e}")
                messagebox.showerror("File Error", f"Could not read prior year Excel file: {e}")
        elif file_path.lower().endswith('.pdf'):
            self.log_message(f"Simulating PDF parsing for prior year financials from: {os.path.basename(file_path)}")
            # --- COMPLEX PDF PARSING LOGIC WOULD GO HERE ---
            # In a real application, you would use libraries like 'pdfminer.six', 'PyPDF2' for text extraction,
            # possibly combined with OCR (e.g., 'Tesseract' via 'Pillow'/'pytesseract') for image-based PDFs,
            # and then advanced regex or NLP techniques to extract structured financial data.
            # For this simulation, we'll just indicate a placeholder result.
            prior_year_data['pdf_status'] = 'PDF parsing simulated. Actual parsing needs advanced logic.'
            prior_year_data['example_figure'] = 123456.78 # Example of a value that might be extracted
            self.log_message("PDF parsing simulated. Actual implementation is complex.")
        return prior_year_data

    def _process_trial_balance_data(self, file_path):
        """
        Processes current year trial balance data from an Excel or CSV file.
        Returns a DataFrame containing the trial balance.
        """
        self.log_message(f"Reading Trial Balance from: {os.path.basename(file_path)}")
        try:
            if file_path.lower().endswith('.xlsx'):
                df = pd.read_excel(file_path)
            elif file_path.lower().endswith('.csv'):
                df = pd.read_csv(file_path)
            else:
                raise ValueError("Unsupported file type for Trial Balance. Must be .xlsx or .csv")
            self.log_message(f"Trial Balance loaded successfully. Rows: {len(df)}")
            return df
        except Exception as e:
            self.log_message(f"Error reading Trial Balance file: {e}")
            messagebox.showerror("File Error", f"Could not read Trial Balance file: {e}")
            return pd.DataFrame() # Return empty DataFrame on error

    def _process_draft_bs_pl_data(self, file_path):
        """
        Processes current year Draft Balance Sheet and P&L data from an Excel file.
        Returns a dictionary of DataFrames (e.g., {'balance_sheet': df_bs, 'p_l': df_pl}).
        """
        self.log_message(f"Reading Draft Balance Sheet & P&L from: {os.path.basename(file_path)}")
        data = {}
        try:
            # Assuming Balance Sheet and P&L are on separate sheets, or can be identified.
            # For simplicity, let's try to read two sheets if they exist.
            excel_file = pd.ExcelFile(file_path)
            if 'Balance Sheet' in excel_file.sheet_names:
                data['balance_sheet'] = excel_file.parse('Balance Sheet')
                self.log_message(f"Loaded Balance Sheet. Rows: {len(data['balance_sheet'])}")
            if 'P&L' in excel_file.sheet_names or 'Profit & Loss' in excel_file.sheet_names:
                sheet_name_pl = 'P&L' if 'P&L' in excel_file.sheet_names else 'Profit & Loss'
                data['profit_loss'] = excel_file.parse(sheet_name_pl)
                self.log_message(f"Loaded Profit & Loss. Rows: {len(data['profit_loss'])}")
            if not data:
                # If specific sheets not found, load the first sheet as a fallback
                self.log_message("Specific 'Balance Sheet' or 'P&L' sheets not found, loading first sheet.")
                data['general_data'] = pd.read_excel(file_path)

            self.log_message("Draft Balance Sheet & P&L loaded successfully.")
            return data
        except Exception as e:
            self.log_message(f"Error reading Draft Balance Sheet & P&L file: {e}")
            messagebox.showerror("File Error", f"Could not read Draft Balance Sheet & P&L file: {e}")
            return {}

    def _calculate_it_depreciation_non_corporate(self, it_block_file):
        """
        Calculates depreciation as per Income Tax Act 1961 for non-corporate entities.
        (Placeholder for actual calculation logic).
        """
        self.log_message(f"Calculating IT depreciation for non-corporate entity using {os.path.basename(it_block_file)} (simulated).")
        try:
            # In a real scenario, read the block register, apply IT depreciation rules
            # For now, simulate a result
            depreciation_amount = 150000.00
            it_depreciation_data = {'it_depreciation_amount': depreciation_amount, 'source_file': os.path.basename(it_block_file)}
            self.log_message(f"IT Depreciation (simulated): {depreciation_amount}")
            return it_depreciation_data
        except Exception as e:
            self.log_message(f"Error calculating IT depreciation for non-corporate: {e}")
            return {}

    def _calculate_companies_act_depreciation(self, schedule_ii_file):
        """
        Calculates depreciation as per Companies Act 2013 (Schedule II).
        (Placeholder for actual calculation logic, highly complex).
        """
        self.log_message(f"Calculating Companies Act depreciation using {os.path.basename(schedule_ii_file)} (simulated).")
        try:
            # This involves reading asset details, useful lives, residual values, and applying Schedule II rates/methods.
            # Simulate a result for demonstration
            depreciation_amount = 200000.00
            co_depreciation_data = {'co_depreciation_amount': depreciation_amount, 'source_file': os.path.basename(schedule_ii_file)}
            self.log_message(f"Companies Act Depreciation (simulated): {depreciation_amount}")
            return co_depreciation_data
        except Exception as e:
            self.log_message(f"Error calculating Companies Act depreciation: {e}")
            return {}

    def _calculate_it_depreciation_company(self, it_wdv_file):
        """
        Calculates depreciation for companies as per Income Tax Act (WDV).
        (Placeholder for actual calculation logic).
        """
        self.log_message(f"Calculating IT depreciation for company using {os.path.basename(it_wdv_file)} (simulated).")
        try:
            # This involves reading the WDV schedule, applying IT depreciation rates on block of assets.
            # Simulate a result for demonstration
            depreciation_amount = 180000.00
            it_wdv_depreciation_data = {'it_wdv_depreciation_amount': depreciation_amount, 'source_file': os.path.basename(it_wdv_file)}
            self.log_message(f"IT WDV Depreciation (simulated): {depreciation_amount}")
            return it_wdv_depreciation_data
        except Exception as e:
            self.log_message(f"Error calculating IT WDV depreciation for company: {e}")
            return {}

    def _write_financial_statements_to_excel(self, output_filename, template_df, prior_year_data, current_year_data, depreciation_data):
        """
        Combines all processed data and generates the final Excel financial statement.
        (Placeholder for actual Excel writing and formatting logic).
        """
        self.log_message(f"Writing financial statements to Excel file: {output_filename} (simulated).")
        try:
            # In a real scenario, this would involve:
            # 1. Creating an Excel workbook (e.g., using openpyxl.Workbook or xlsxwriter.Workbook)
            # 2. Populating sheets based on template_df structure.
            # 3. Inserting current_year_data and prior_year_data into the appropriate cells.
            # 4. Applying calculated depreciation figures.
            # 5. Adding formulas, formatting (fonts, colors, borders), headers, footers.
            # 6. Saving the workbook.

            # For now, just create a dummy Excel file with a message
            with pd.ExcelWriter(output_filename, engine='xlsxwriter') as writer:
                summary_df = pd.DataFrame({
                    'Step': ['Formatting', 'Prior Year', 'Current Year', 'Depreciation'],
                    'Status': ['Processed', 'Processed' if prior_year_data else 'Skipped', 'Processed' if current_year_data else 'Skipped', 'Processed' if depreciation_data else 'Skipped'],
                    'Details': [
                        f"Template rows: {len(template_df)}",
                        f"Prior Year Data: {prior_year_data.get('pdf_status', 'N/A') if 'pdf_status' in prior_year_data else 'Data Loaded'}",
                        f"Current Year TB: {len(current_year_data.get('trial_balance', pd.DataFrame()))} rows",
                        f"IT Dep: {depreciation_data.get('it_depreciation', {}).get('it_depreciation_amount', 'N/A')}"
                    ]
                })
                summary_df.to_excel(writer, sheet_name='Summary', index=False)

            self.log_message(f"Simulated Excel file '{output_filename}' created successfully.")
            return True
        except Exception as e:
            self.log_message(f"Error generating Excel file: {e}")
            messagebox.showerror("Excel Generation Error", f"Could not generate Excel file: {e}")
            return False

    def generate_financial_statements(self):
        self.log_message("Starting financial statement generation...")
        self.progress_bar.set(0)

        # 1. Gather all inputs from the UI
        entity_name = self.entity_name_entry.get()
        assessment_year = self.assessment_year_entry.get()
        financial_year = self.financial_year_entry.get()
        entity_type = self.entity_type_var.get()
        formatting_option = self.formatting_option_var.get()
        prior_year_data_available = self.prior_year_data_available_var.get()
        current_year_source = self.current_year_source_var.get()

        self.log_message(f"Entity: {entity_name}, Type: {entity_type}, FY: {financial_year}, AY: {assessment_year}")
        self.log_message(f"Formatting Option: {formatting_option}")
        self.log_message(f"Prior Year Data Available: {prior_year_data_available}")
        self.log_message(f"Current Year Data Source: {current_year_source}")

        # 2. Implement Formatting Logic (Step 2)
        self.progress_bar.set(0.1)
        self.log_message("Processing formatting master...")
        template_df = pd.DataFrame() # Initialize an empty DataFrame

        if formatting_option == "standard":
            self.log_message("Using standard ICAI / Schedule III template.")
            template_df = self._load_standard_template(entity_type)
            self.log_message(f"Standard template loaded with {len(template_df)} rows and {len(template_df.columns)} columns.")
        elif formatting_option == "custom":
            custom_file = self.file_paths["custom_formatting_file"]
            if custom_file and os.path.exists(custom_file):
                self.log_message(f"Cloning layout from custom file: {os.path.basename(custom_file)}")
                try:
                    template_df = pd.read_excel(custom_file)
                    self.log_message(f"Custom template loaded from {os.path.basename(custom_file)} with {len(template_df)} rows and {len(template_df.columns)} columns.")
                except Exception as e:
                    self.log_message(f"Error loading custom formatting file: {e}")
                    messagebox.showerror("File Error", f"Could not load custom formatting file: {e}")
                    return # Stop generation on error
            else:
                self.log_message("No valid custom formatting file selected. Using a basic placeholder template.")
                template_df = pd.DataFrame({'Note': ['No custom file provided, using basic placeholder.']})
        self.update_idletasks()

        # 3. Process Prior Year Figures (Step 3)
        self.progress_bar.set(0.25)
        self.log_message("Processing prior year figures...")
        prior_year_data = {} # Placeholder for prior year financial data
        if prior_year_data_available:
            prior_year_file = self.file_paths["prior_year_financials_file"]
            if prior_year_file and os.path.exists(prior_year_file):
                prior_year_data = self._process_prior_year_financials(prior_year_file)
                self.log_message(f"Prior year data processed. Keys: {list(prior_year_data.keys())}")
            else:
                self.log_message("Prior year data toggled ON, but no valid file selected or file does not exist.")
        else:
            self.log_message("Prior year data not available/toggled OFF.")
        self.update_idletasks()

        # 4. Process Current Year Data Ingestion (Step 4)
        self.progress_bar.set(0.4)
        self.log_message("Processing current year data...")
        current_year_data = {} # Placeholder for current year financial data
        if current_year_source == "trial_balance":
            tb_file = self.file_paths["current_year_trial_balance_file"]
            if tb_file and os.path.exists(tb_file):
                current_year_data['trial_balance'] = self._process_trial_balance_data(tb_file)
                if not current_year_data['trial_balance'].empty:
                    self.log_message("Trial Balance data successfully loaded into current_year_data.")
            else:
                self.log_message("No valid Trial Balance file selected or file does not exist.")
        elif current_year_source == "draft_bs_pl":
            draft_file = self.file_paths["current_year_draft_bs_pl_file"]
            if draft_file and os.path.exists(draft_file):
                current_year_data['draft_bs_pl'] = self._process_draft_bs_pl_data(draft_file)
                if current_year_data['draft_bs_pl']:
                    self.log_message("Draft Balance Sheet & P&L data successfully loaded into current_year_data.")
            else:
                self.log_message("No valid Draft Balance Sheet & P&L file selected or file does not exist.")
        elif current_year_source == "tally_prime":
            self.log_message("Attempting to fetch data directly from Tally Prime (simulated).")
            # Logic for Tally Prime integration (needs a separate service/API call)
            current_year_data['tally_data'] = {'status': 'Tally Prime data fetch simulated'}
            self.log_message("Simulated Tally Prime data fetch completed.")
        # Other accounting software (SAP/Oracle) would extend this logic
        self.update_idletasks()

        # 5. Process Depreciation Engine Options (Step 5)
        self.progress_bar.set(0.6)
        self.log_message("Calculating depreciation...")
        depreciation_data = {} # Placeholder for depreciation calculation results
        if entity_type in ["Proprietorship", "Partnership Firm", "Trust"]:
            self.log_message("Entity is Non-Corporate. Calculating depreciation as per Income Tax Act 1961.")
            it_block_file = self.file_paths["income_tax_block_register_file"]
            if it_block_file and os.path.exists(it_block_file):
                depreciation_data['it_depreciation'] = self._calculate_it_depreciation_non_corporate(it_block_file)
                self.log_message(f"Non-corporate IT depreciation calculated: {depreciation_data['it_depreciation']}")
            else:
                self.log_message("Income Tax Block Register not provided for non-corporate entity or file does not exist. Skipping IT depreciation calculation.")
        elif entity_type == "Private Limited / Limited Company":
            self.log_message("Entity is a Company. Calculating dual depreciation (Companies Act & Income Tax Act).")
            schedule_ii_file = self.file_paths["schedule_ii_asset_register_file"]
            it_wdv_file = self.file_paths["income_tax_wdv_schedule_file"]

            if schedule_ii_file and os.path.exists(schedule_ii_file):
                depreciation_data['co_depreciation'] = self._calculate_companies_act_depreciation(schedule_ii_file)
                self.log_message(f"Companies Act depreciation calculated: {depreciation_data['co_depreciation']}")
            else:
                self.log_message("Schedule II Asset Register not provided for company or file does not exist. Skipping Companies Act depreciation calculation.")

            if it_wdv_file and os.path.exists(it_wdv_file):
                depreciation_data['it_depreciation_company'] = self._calculate_it_depreciation_company(it_wdv_file)
                self.log_message(f"Company IT WDV depreciation calculated: {depreciation_data['it_depreciation_company']}")
            else:
                self.log_message("Income Tax WDV Schedule not provided for company or file does not exist. Skipping Company IT WDV depreciation calculation.")

            if not (schedule_ii_file and it_wdv_file and os.path.exists(schedule_ii_file) and os.path.exists(it_wdv_file)):
                self.log_message("Both Schedule II Asset Register and Income Tax WDV Schedule are recommended for companies for dual depreciation calculation. Please provide both for complete results.")

        self.update_idletasks()

        # 6. Generate the Financial Statements (Integration and Output)
        self.progress_bar.set(0.8)
        self.log_message("Integrating data and generating final Excel report...")
        output_filename = f"Financial_Statements_{entity_name}_{financial_year}.xlsx"

        # Call the new helper method to write to Excel
        if self._write_financial_statements_to_excel(output_filename, template_df, prior_year_data, current_year_data, depreciation_data):
            self.progress_bar.set(1.0)
            self.log_message(f"Financial statements generated successfully (simulated) as {output_filename}!")
            messagebox.showinfo("Generation Complete", f"Financial statements have been generated as {output_filename}.")
        else:
            self.log_message("Financial statement generation failed.")
            messagebox.showerror("Generation Failed", "Failed to generate financial statements.")

        self.update_idletasks()


if __name__ == "__main__":
    # Ensure the script is run in an environment where `customtkinter` can create a GUI window.
    # In Colab, this typically means the GUI will not display directly without specific setup (e.g., `colab_xserver`).
    # For local execution, uncomment the line below:
    # ctk.set_appearance_mode("System") # Modes: "System" (default), "Dark", "Light"
    # ctk.set_default_color_theme("blue") # Themes: "blue" (default), "dark-blue", "green"

    pass # No GUI execution in Colab environment